### ISSUE TITLE
Cone behaves weird

### ISSUE THREAD

**Issue by vajpeters** [physicsdavid/mPicker#1]
After some debugging I found in the cone statement:
mPage.rotateX(PI);
Is this correct? Why is this used here?

After removing everything seemed to behave as expected...

**Comment by physicsdavid** [comment]
When I wrote the code, there seemed to be a bug that occurred when drawing cones in some circumstances. I think it would invert the cone but now I can't recall the exact details and I didn't document that, obviously. Now that I try it again, I can't seem to replicate the old bug and so wonder if I might have been compensating for a bug in the p5.js core that I should have addressed with an issue but has now been fixed. Even so, I now can't logically see why that would have fixed it. I think it should probably just be removed and will do that now. Thanks!
